/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: NetSimProto.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "NetSimProto.pb-c.h"
void   init_msg__init
                     (InitMsg         *message)
{
  static const InitMsg init_value = INIT_MSG__INIT;
  *message = init_value;
}
size_t init_msg__get_packed_size
                     (const InitMsg *message)
{
  assert(message->base.descriptor == &init_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t init_msg__pack
                     (const InitMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &init_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t init_msg__pack_to_buffer
                     (const InitMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &init_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InitMsg *
       init_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InitMsg *)
     protobuf_c_message_unpack (&init_msg__descriptor,
                                allocator, len, data);
}
void   init_msg__free_unpacked
                     (InitMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &init_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   act_msg__init
                     (ActMsg         *message)
{
  static const ActMsg init_value = ACT_MSG__INIT;
  *message = init_value;
}
size_t act_msg__get_packed_size
                     (const ActMsg *message)
{
  assert(message->base.descriptor == &act_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t act_msg__pack
                     (const ActMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &act_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t act_msg__pack_to_buffer
                     (const ActMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &act_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActMsg *
       act_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActMsg *)
     protobuf_c_message_unpack (&act_msg__descriptor,
                                allocator, len, data);
}
void   act_msg__free_unpacked
                     (ActMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &act_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obs_msg__init
                     (ObsMsg         *message)
{
  static const ObsMsg init_value = OBS_MSG__INIT;
  *message = init_value;
}
size_t obs_msg__get_packed_size
                     (const ObsMsg *message)
{
  assert(message->base.descriptor == &obs_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obs_msg__pack
                     (const ObsMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &obs_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obs_msg__pack_to_buffer
                     (const ObsMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &obs_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObsMsg *
       obs_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObsMsg *)
     protobuf_c_message_unpack (&obs_msg__descriptor,
                                allocator, len, data);
}
void   obs_msg__free_unpacked
                     (ObsMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &obs_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   python_msg__init
                     (PythonMsg         *message)
{
  static const PythonMsg init_value = PYTHON_MSG__INIT;
  *message = init_value;
}
size_t python_msg__get_packed_size
                     (const PythonMsg *message)
{
  assert(message->base.descriptor == &python_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t python_msg__pack
                     (const PythonMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &python_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t python_msg__pack_to_buffer
                     (const PythonMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &python_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PythonMsg *
       python_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PythonMsg *)
     protobuf_c_message_unpack (&python_msg__descriptor,
                                allocator, len, data);
}
void   python_msg__free_unpacked
                     (PythonMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &python_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_sim_msg__init
                     (NetSimMsg         *message)
{
  static const NetSimMsg init_value = NET_SIM_MSG__INIT;
  *message = init_value;
}
size_t net_sim_msg__get_packed_size
                     (const NetSimMsg *message)
{
  assert(message->base.descriptor == &net_sim_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_sim_msg__pack
                     (const NetSimMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_sim_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_sim_msg__pack_to_buffer
                     (const NetSimMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_sim_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetSimMsg *
       net_sim_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetSimMsg *)
     protobuf_c_message_unpack (&net_sim_msg__descriptor,
                                allocator, len, data);
}
void   net_sim_msg__free_unpacked
                     (NetSimMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &net_sim_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor init_msg__field_descriptors[5] =
{
  {
    "time_step",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(InitMsg, time_step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(InitMsg, total_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command_name",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(InitMsg, n_command_name),
    offsetof(InitMsg, command_name),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_name",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(InitMsg, n_device_name),
    offsetof(InitMsg, device_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numofagent",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(InitMsg, numofagent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned init_msg__field_indices_by_name[] = {
  2,   /* field[2] = command_name */
  3,   /* field[3] = device_name */
  4,   /* field[4] = numofagent */
  0,   /* field[0] = time_step */
  1,   /* field[1] = total_time */
};
static const ProtobufCIntRange init_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor init_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InitMsg",
  "InitMsg",
  "InitMsg",
  "",
  sizeof(InitMsg),
  5,
  init_msg__field_descriptors,
  init_msg__field_indices_by_name,
  1,  init_msg__number_ranges,
  (ProtobufCMessageInit) init_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor act_msg__field_descriptors[3] =
{
  {
    "command_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ActMsg, command_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ActMsg, n_values),
    offsetof(ActMsg, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doneinfo",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ActMsg, doneinfo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned act_msg__field_indices_by_name[] = {
  0,   /* field[0] = command_name */
  2,   /* field[2] = doneinfo */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange act_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor act_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActMsg",
  "ActMsg",
  "ActMsg",
  "",
  sizeof(ActMsg),
  3,
  act_msg__field_descriptors,
  act_msg__field_indices_by_name,
  1,  act_msg__number_ranges,
  (ProtobufCMessageInit) act_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obs_msg__field_descriptors[3] =
{
  {
    "is_reward",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ObsMsg, is_reward),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ObsMsg, key_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ObsMsg, n_values),
    offsetof(ObsMsg, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obs_msg__field_indices_by_name[] = {
  0,   /* field[0] = is_reward */
  1,   /* field[1] = key_name */
  2,   /* field[2] = values */
};
static const ProtobufCIntRange obs_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor obs_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ObsMsg",
  "ObsMsg",
  "ObsMsg",
  "",
  sizeof(ObsMsg),
  3,
  obs_msg__field_descriptors,
  obs_msg__field_indices_by_name,
  1,  obs_msg__number_ranges,
  (ProtobufCMessageInit) obs_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor python_msg__field_descriptors[3] =
{
  {
    "is_init",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PythonMsg, is_init),
    &is_init__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PythonMsg, n_details),
    offsetof(PythonMsg, details),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_sim",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PythonMsg, stop_sim),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned python_msg__field_indices_by_name[] = {
  1,   /* field[1] = details */
  0,   /* field[0] = is_init */
  2,   /* field[2] = stop_sim */
};
static const ProtobufCIntRange python_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor python_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PythonMsg",
  "PythonMsg",
  "PythonMsg",
  "",
  sizeof(PythonMsg),
  3,
  python_msg__field_descriptors,
  python_msg__field_indices_by_name,
  1,  python_msg__number_ranges,
  (ProtobufCMessageInit) python_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor net_sim_msg__field_descriptors[4] =
{
  {
    "key_num",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetSimMsg, key_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetSimMsg, n_details),
    offsetof(NetSimMsg, details),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_done",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NetSimMsg, is_done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "more_info",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetSimMsg, more_info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_sim_msg__field_indices_by_name[] = {
  1,   /* field[1] = details */
  2,   /* field[2] = is_done */
  0,   /* field[0] = key_num */
  3,   /* field[3] = more_info */
};
static const ProtobufCIntRange net_sim_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor net_sim_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetSimMsg",
  "NetSimMsg",
  "NetSimMsg",
  "",
  sizeof(NetSimMsg),
  4,
  net_sim_msg__field_descriptors,
  net_sim_msg__field_indices_by_name,
  1,  net_sim_msg__number_ranges,
  (ProtobufCMessageInit) net_sim_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue is_init__enum_values_by_number[2] =
{
  { "IsInit_Act", "IS_INIT__IsInit_Act", 0 },
  { "IsInit_Init", "IS_INIT__IsInit_Init", 1 },
};
static const ProtobufCIntRange is_init__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex is_init__enum_values_by_name[2] =
{
  { "IsInit_Act", 0 },
  { "IsInit_Init", 1 },
};
const ProtobufCEnumDescriptor is_init__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IsInit",
  "IsInit",
  "IsInit",
  "",
  2,
  is_init__enum_values_by_number,
  2,
  is_init__enum_values_by_name,
  1,
  is_init__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
