# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetSimProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11NetSimProto.proto\x1a\x19google/protobuf/any.proto\"o\n\x07InitMsg\x12\x11\n\ttime_step\x18\x01 \x01(\x02\x12\x12\n\ntotal_time\x18\x02 \x01(\x02\x12\x14\n\x0c\x63ommand_name\x18\x03 \x03(\x05\x12\x13\n\x0b\x64\x65vice_name\x18\x04 \x03(\t\x12\x12\n\nnumofagent\x18\x05 \x01(\x05\"@\n\x06\x41\x63tMsg\x12\x14\n\x0c\x63ommand_name\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x10\n\x08\x64oneinfo\x18\x03 \x01(\x05\"=\n\x06ObsMsg\x12\x11\n\tis_reward\x18\x01 \x01(\x08\x12\x10\n\x08key_name\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\x02\"^\n\tPythonMsg\x12\x18\n\x07is_init\x18\x01 \x01(\x0e\x32\x07.IsInit\x12%\n\x07\x64\x65tails\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08stop_sim\x18\x03 \x01(\x08\"g\n\tNetSimMsg\x12\x0f\n\x07key_num\x18\x01 \x01(\x05\x12%\n\x07\x64\x65tails\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x0f\n\x07is_done\x18\x03 \x01(\x08\x12\x11\n\tmore_info\x18\x04 \x01(\t*)\n\x06IsInit\x12\x0e\n\nIsInit_Act\x10\x00\x12\x0f\n\x0bIsInit_Init\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NetSimProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ISINIT._serialized_start=491
  _ISINIT._serialized_end=532
  _INITMSG._serialized_start=48
  _INITMSG._serialized_end=159
  _ACTMSG._serialized_start=161
  _ACTMSG._serialized_end=225
  _OBSMSG._serialized_start=227
  _OBSMSG._serialized_end=288
  _PYTHONMSG._serialized_start=290
  _PYTHONMSG._serialized_end=384
  _NETSIMMSG._serialized_start=386
  _NETSIMMSG._serialized_end=489
# @@protoc_insertion_point(module_scope)
